apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
  labels:
    component: events
spec:
  replicas: 2
  selector:
    matchLabels:
      component: events
  template:
    metadata:
      labels:
        component: events
    spec:
      containers:
      - name: events
        image: gcr.io/roi-training-treder-gke/events-service
        ports:
        - containerPort: 3001
