apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    component: users
spec:
  replicas: 2
  selector:
    matchLabels:
      component: users
  template:
    metadata:
      labels:
        component: users
    spec:
      containers:
      - name: users
        image: gcr.io/roi-training-treder-gke/users-service
        ports:
        - containerPort: 3002
